# -*- coding: utf-8 -*-
"""SIF2500341 Python Lab Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xaYbwRtLLk_2v_tvkd136zR4w33tPw5w
"""

student_name = input("Enter Student Name: ")
student_id =  input("Enter Student ID: ")
total_classes = int(input("Enter Total Classes Held: "))
classes_attended = int(input("Enter Classes Attended: "))

if total_classes <= 0:
    print("Error: Total classes must be greater than 0.")

elif classes_attended < 0 or classes_attended > total_classes:
    print("Error: Invalid number of attended classes.")

else:
    attendance_percentage = (classes_attended / total_classes) * 100

    print("\nStudent Name:", student_name)
    print("Total Classes:", total_classes)
    print("Classes Attended:", classes_attended)

    if attendance_percentage >= 75:
        print("Allowed for exam")
    else:
        print("Not allowed for exam")